Env:
  id: LunarLander-v2
  new_step_api: true 
Trainer:
  buffer_size: 20000
  batch_size: 256
  device: cpu
  num_epochs: 20000
  name: LunarLander-v2
  policy_net: MLP
  policy_net_kwargs:
    hidden_size: 64
    num_layers: 2
  critic_net: MLP
  critic_net_kwargs:
    hidden_size: 64
    num_layers: 2
  learning_rate: 0.0005
  discount: 0.99
