Env:
  id: Pendulum-v1
  new_step_api: False,
Trainer:
  buffer_size: 1000000
  batch_size: 64
  device: cuda
  max_episode_steps: 500
  num_episodes: 2000
  name: Pendulum-v1
  policy_lr: 0.0001
  critic_lr: 0.0001 #1e-4 in iq-learn, 1e-3 for DDPG
  discount: 0.99
  soft_update_tau: 0.001
  save: True
