Env:
  id: Pendulum-v1
  new_step_api: true,
Trainer:
  buffer_size: 10000
  batch_size: 64
  device: cuda
  max_episode_steps: 300
  num_episodes: 100000
  name: Pendulum-v1
  policy_lr: 0.001
  critic_lr: 0.001
  discount: 0.99
  soft_update_tau: 0.001
