Env:
  id: simple_adversary_v2
  N: 2
  max_cycles: 25
  continuous_actions: false
Trainer:
  buffer_size: 1000000
  batch_size: 64
  device: cpu
  max_episode_steps: 200
  num_episodes: 1000
  name: Simple_Adversary_v2
  policy_lr: 0.0001
  critic_lr: 0.001
  discount: 0.99
  soft_update_tau: 0.001